M48
; DRILL file {KiCad 8.0.2} date 2025-12-20T16:44:12-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-20T16:44:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.487Y-3.837
X4.537Y-1.937
X6.537Y-2.537
X6.537Y-3.637
M30
